qcheck random seed: 1234
Testing `my test'.
  [OK]          suite              0   list_rev_is_involutive.
  [FAIL]        suite              1   fail_sort_id.
  [FAIL]        suite              2   error_raise_exn.
  [FAIL]        suite              3   fail_check_err_message.
  [OK]          suite              4   tree_rev_is_involutive.
  [FAIL]        shrinking          0   debug_shrink.
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite              1   fail_sort_id.                           │
└──────────────────────────────────────────────────────────────────────────────┘
test `fail_sort_id` failed on ≥ 1 cases: [1; 0] (after 11 shrink steps)
[exception] test `fail_sort_id` failed on ≥ 1 cases: [1; 0] (after 11 shrink steps)
 ──────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite              2   error_raise_exn.                        │
└──────────────────────────────────────────────────────────────────────────────┘
test `error_raise_exn`
raised exception `Error`
on `0 (after 1 shrink steps)`
[exception] test `error_raise_exn`
raised exception `Error`
on `0 (after 1 shrink steps)`
 ──────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite              3   fail_check_err_message.                 │
└──────────────────────────────────────────────────────────────────────────────┘
test `fail_check_err_message` failed on ≥ 1 cases:
0 (after 1 shrink steps)
this
will
always
fail
[exception] test `fail_check_err_message` failed on ≥ 1 cases:
0 (after 1 shrink steps)
this
will
always
fail
 ──────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        shrinking          0   debug_shrink.                           │
└──────────────────────────────────────────────────────────────────────────────┘
~~~ Shrink ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test debug_shrink successfully shrunk counter example (step 0) to:
(3, 1)
~~~ Shrink ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test debug_shrink successfully shrunk counter example (step 1) to:
(0, 1)
law debug_shrink: 2 relevant cases (2 total)
test `debug_shrink` failed on ≥ 1 cases: (0, 1) (after 1 shrink steps)
[exception] test `debug_shrink` failed on ≥ 1 cases: (0, 1) (after 1 shrink steps)
 ──────────────────────────────────────────────────────────────────────────────
4 failures! 6 tests run.
